[package]
name = "shacl"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "A high-performance SHACL validation engine"

[dependencies]
oxrdf.workspace = true
oxrdfio.workspace = true
oxttl = { version = "0.2", features = ["rdf-12"] }
oxsdatatypes.workspace = true
spargebra.workspace = true
spareval.workspace = true
rayon.workspace = true
hashbrown.workspace = true
regex.workspace = true


[dev-dependencies]
mimalloc = { version = "0.1", default-features = false }
anyhow.workspace = true
